name: VSIX

on:
  schedule:
    - cron: '0 0 * * *'

  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install VSCE
        run: sudo npm i -g vsce

      - name: Package VSIX
        run: vsce package -o vs-code-theme.vsix

      - uses: actions/upload-artifact@v1
        with:
          name: vs-code-theme.vsix
          path: vs-code-theme.vsix
